version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - translogi-network
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=sudha010274
      - MYSQL_DATABASE=translogi
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MYSQL_PORT=3307
    depends_on:
      - db
    networks:
      - translogi-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: sudha010274
      MYSQL_DATABASE: translogi
      MYSQL_USER: rahulagowda04
      MYSQL_PASSWORD: sudha010274
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - translogi-network

networks:
  translogi-network:
    driver: bridge

volumes:
  mysql-data:
  frontend_node_modules:
