version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - NAME=World
    command:
      [
        "pm2-runtime",
        "start",
        "app.py",
        "--interpreter",
        "python3",
        "--name",
        "app",
        "--",
        "&&",
        "npm",
        "run",
        "dev",
      ]
